# ROI coordinates for 1280x720 video
# Horizontal throttle/brake bars in bottom-right corner

# Throttle - horizontal bar (green/yellow/orange when TC active)
throttle:
  x: 1170
  y: 670
  width: 103
  height: 14

# Brake - horizontal bar below throttle (red/yellow/orange when ABS active)
# Height reduced to 11 to avoid capturing Force Feedback indicator below
brake:
  x: 1170
  y: 687
  width: 103
  height: 11

# Steering - white dot on horizontal scale above throttle bar
# Extended to frame edge to capture rightmost tick marks (x=1110 to x=1280)
steering:
  x: 1135
  y: 662
  width: 134
  height: 9

